name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: yaCloud-s3
    steps:
    - uses: actions/checkout@master
    - name: Upload file to bucket
      uses: koraykoska/s3-upload-github-action@master
      env:
          FILE: ./.html-build/
          S3_ENDPOINT: 'https://storage.yandexcloud.net'
          S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #comment
